# icons_format = "{icon} "

[theme]
theme = "slick"
# theme = "solarized-dark"

[icons]
icons = "awesome5"
[icons.overrides]
net_wired = "\uf0ac"

[[block]]
block = "custom"
command = "[[ -e /proc/sys/net/ipv4/conf/eth0 ]] && eth0_ip=$(ip -json -family inet6 address show eth0 scope global |jq -r '.[].addr_info[0].local') && echo '{\"icon\":\"net_wired\", \"text\": \"'$eth0_ip' ('$(cat /sys/class/net/eth0/speed)'Mb/s)\"}' || echo '{\"icon\":\"net_wired\", \"state\":\"Idle\", \"text\": \"not connected\"}'"
json = true
interval = 1800

[[block]]
block = "custom"
command = "[[ -e /proc/sys/net/ipv4/conf/tun0 ]] && tun0_ip=$(ip -json -family inet address show tun0 |jq -r '.[].addr_info[].local') && echo '{\"icon\":\"net_vpn\", \"state\":\"Good\", \"text\": \"VPN ('\"$tun0_ip\"')\"}' || echo '{\"icon\":\"net_vpn\", \"state\":\"Idle\", \"text\": \"no\"}'"
json = true
interval = 20

[[block]]
block = "disk_space"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon $swap_used_percents.eng(w:2) "

[[block]]
block = "load"
interval = 1

[[block]]
block = "temperature"
interval = 10
format = " $icon $average|"
chip = "k10temp-*"
inputs = ["Tctl"]

[[block]]
block = "temperature"
interval = 10
format = " $icon $average|"
chip = "amdgpu-*"
inputs = ["edge"]

[[block]]
block = "custom"
format = " \uf028 $text.pango-str() "
command = "wpctl get-volume @DEFAULT_AUDIO_SINK@ |awk '{ print $NF * 100 \"%\"}'"
# cycle= ["wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && vol=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ |awk '{ print $NF * 100 \"%\"}') && echo '{\"icon\": \"volume\", \"text\": \"'$vol'\"}'", "wpctl set-mute @DEFAULT_AUDIO_SINK@ 1 && echo '{\"icon\": \"headphones\", \"text\": \"\"}'"]
# json = true
[[block.click]]
button = "up"
cmd = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+"
update = true
[[block.click]]
button = "down"
cmd = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"
update = true
[[block.click]]
button = "left"
cmd = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
update = true
# action = "cycle"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d.%m. %R')"
short = " $icon $timestamp.datetime(f:'%R')"
